### ISSUE TITLE
Can the WIP Vuforia project be shared?

### ISSUE THREAD

**Issue by tejaskumar31** [ChristophGeske/ARCoreInsideOutTrackingGearVr#18]
Hello,

Thank you for all your work into bringing positional tracking to the Gear VR. You said in your README that you'd be willing to share your WIP Vuforia marker controller tracking project. I'm working on something similar and any additional information would be useful.

**Comment by ChristophGeske** [comment]
Sorry for late reply I just started working on the project again. Unfortunately I had some problems with unity crashing and destroying the project. Since I did not made a backup on github I lost the marker tracking project. 

You might found out yourself by now how to do it. If not here is a short outline how to do it. 
1. Use Unity version 2018.2 which supports Vuforia fusion and import Vuforia directly when installing Unity. ArCore is than directly included with the latest Vuforia version 7.2. I had some trouble finding the correct version since the one that comes included in Unity 2018.2 is an older version. ArCore is only included in the newer version Vuforia 7.2. Make sure to check if the vuforia version in unity is 7.2 or higher. If not you have to import the higher version yourself.
More infos can be found here:
https://library.vuforia.com/articles/Training/vuforia-fusion-article.html
https://library.vuforia.com/articles/Training/getting-started-with-vuforia-in-unity.html#betas
3. Import the GoogleVR or GearVR packages depending on your platform and if you want to make a VR project.
4. If you need both head tracking and marker tracking use the vuforia fusion camera like you would use the ARCore Camera in the other projects for head tracking. This means you use the vuforia camera for positioning in space and you follow with a second camera to smooth the movement.
4. Set up your vuforia marker. I found this video helpful. 
https://www.youtube.com/watch?v=MtiUx_szKbI
5. When you want to use ARCore in combination with Vuforia some extra steps need to be taken. Like explained here: https://library.vuforia.com/content/vuforia-library/en/articles/Solution/arcore-with-vuforia.html

As far as I can remember these are the most important steps but it's some time ago and I might missed something important so please check everything yourself and don't fully rely on my list.
If I find time to experiment with it in the future again I will upload my work earlier so it can be used by others and I don't loose it again ;)

Greetings 
Christoph

**Comment by ChristophGeske** [comment]
I revisited and rebuild the Moving Marker project so if you are still interested you can find it here:
https://github.com/ChristophGeske/ARCoreInsideOutTrackingGearVr/tree/master/MovingMarkerTracking

If you use a GearVR you can run this apk after signing it:
MovingMarkerTracking.apk

The King.jpg is the moving marker that gets tracked.

The version has some bugs and is not very pretty but it is a minimal working solution for 6DOF moving marker tracking in combination with 6DOF head tracking in VR.
