### ISSUE TITLE
Camera Set Up Guide

### ISSUE THREAD

**Issue by fromzed** [ChristophGeske/ARCoreInsideOutTrackingGearVr#25]
Is there any chance you send me a guide on how to set up the ARCore Device Object as well as the UserCamera? I had a few things go wrong while importing but I've gotten everything working and I just wanted to make sure I had everything set up the same. If you pass this on to me, I am willing to help out with the project. Especially by making some guides ( pdf and video) for setting the project up, modifying it as well as some videos that who what it can be turned into. Please lmk, this is absolutely amazing work.

**Comment by ChristophGeske** [comment]
The ARCore Device and UserCamera objects should be set up correctly if you import the project with Unity. Did you experience Errors when importing and running one of the projects. Where these errors caused by parts of the project (errors in scripts, ..) or did you experience Unity related errors (Missing SDK, Wrong Unity version and such stuff.)
Could you elaborate a bit about the kind of problems you experienced. I think Unity related issues are the most common one. Just using the wrong Unity version or not setting it up correctly can crash the whole project.
Which project did you try I know there is a bunch of them ( "BoxyRoomChardboard", "MovingMarkerTracking", "NativeARCoreTracking(Experimental)", "NativeARCoreTracking(Experimental)", "VikingVillage", "VuforiaTracking(Experimental)" and "WhiteIsland") in the repository and I will clean up a lot with the next update to make it easier to understand the repository.
Are you using a GearVR or Daydream headset.
