### ISSUE TITLE
Can I use it on mirage solo?

### ISSUE THREAD

**Issue by DAangel101** [ChristophGeske/ARCoreInsideOutTrackingGearVr#28]

**Comment by ChristophGeske** [comment]
Simple question but complicated answer.

As far as I know the mirage solo also runs normal daydream apps in 3DOF. You can force 6DOF onto normal daydream apps when they were not specifically built for the mirage solo.
The BoxyRoomCardboard.apk and VikingVillageCardboard.apk are build for Cardboard but with one click in the Unity Engine they can be converted to Daydream apps. I am not sure if I check the box for Daydream support and I don't even know if the apks I listed run on Daydream headsets. If they do not run on Daydream headsets, they also do not run on the Mirage Solo.

The easiest way for you to find out if they run on your headset is to just install the .apk file and see if it works. If they don't work you need to go into the Unity settings and add/switch to Daydream yourself. It would be even better if you nit just switch the project to normal Daydream but directly to Mirage Solo Daydream. This is not complicated if you are familiar with Unity but might be not so trivial if you never used Unity before.
With the next update I will add a specific Daydream .apk to make it easier for Daydream user to find the correct app for them.

When you get the apps running on your headset but you have not enabled the force 6DoF function in the settings they will only be 3DoF like all the other normal Daydream apps you are normally using. The reason is that the positional tracking I use works differently from the one on the Mirage Solo. You would in fact ignore my tracking solution which uses ARCore (not running on the mirage solo). 
But since you can force 6DOF onto every normal Daydream app you can also force your 6DoF on my apps when they are build as Daydream supported apps. If you use my project and change it to a mirage solo project in the settings, it should be directly supported by the Mirage Solo. The differences in developing for Cardboard, Daydream or Mirage solo are very small and switching between the platforms is very easy for developers. 

That's all theoretical I haven't tested this combination so the short answer if it works is yes probably. 
The more important question is if it makes sense for you to do all these steps just to run one of these apps and I would say the answer is no since these are not real games or experiences but rather showcases for a hacked tracking method which is inferior compared to the tracking found on the mirage solo.
I don't think we will reach the tracking quality of the mirage solo any time soon with this hack of the smartphone camera.

All that also means that apps developed for the mirage solo could be easily switched to run on all Daydream, GearVR and Cardboard apps if the developer toggles the right buttons in the unity settings and adds some files found in this repository. It also means that all apps which are developed with this tracking solution can be easily switched over to mirage solo if the developer is interested in doing so.

I will keep the mirage solo in mind if I ever create an app which is more than just a tech demo. But for now this project offers not much for Mirage Solo users.
